layout_spectrum: 0
color:
  saturation: 1
  brandStrength: 0.2692769
  lightness: 0.7204301
  rhythmicContrast: 0.5663083
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.109319
name: Portland Crab
